name: Flutter Build and Release

on:
  push:
    tags:
      - 'v*'


permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Upload Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: mobile/build/app/outputs/flutter-apk/app-release.apk
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false